### ISSUE TITLE
Extended Routes example does not work as described

### ISSUE THREAD

**Issue by synox** [fortrabbit/slimcontroller#26]
When I run the code from the readme:

```
$app->addRoutes(array(
    '/' => array('Home:index', array(function() {
        error_log("MIDDLEWARE FOR SINGLE ROUTE");
    }))
));
```

I get the following exception: 

> PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Http method '0' is not supported.'
## Problem

```
        foreach ($routeArgs as $httpMethod => $classArgs) {
```

it iterates over each $routeArg, and uses the key as httpMethod. But the key of the local Middleware is "0". That's why it can't work. Please update the readme. 

What works for me, is: (but the syntax is a bit messy)

```
$app->addRoutes(array(
    '/'  => array('get' => array('Home:index', function() {}))
));
```

**Comment by savdeep** [comment]
This issue is still appearing on latest release. It must be that i am doing something wrong, but this issue appears as such.

**Comment by savdeep** [comment]
@yaworsw can you please clarify the above doubt?

**Comment by yaworsw** [comment]
Can you post the code you're trying to use?

**Comment by savdeep** [comment]
I used the exact code used in example
// how to integrate the Slim middleware
$app->addRoutes(array(
    '/' => array('Home:index', array(function() {
            error_log("MIDDLEWARE FOR SINGLE ROUTE");
        },
        function() {
            error_log("ADDITIONAL MIDDLEWARE FOR SINGLE ROUTE");
        })
    ),
    '/hello/:name' => array('post' => 'Home:hello', function() {
            error_log("THIS ROUTE IS ONLY POST");
        }
    )
), function() {
    error_log("APPENDED MIDDLEWARE FOR ALL ROUTES");
});
, alternatively i used  below code for my perusal.
 $app->addRoutes(array(
    '/'  => array('get' => array('Home:index', function() {}))
));

**Comment by yaworsw** [comment]
Okay, yep, the `addRoutes` method expects the middlewares to be in the same array as the `controller:action`, not in a separate array.

```php
$application->addRoutes(array(
    '/' => array('get' => array('Home:index', function() {
            error_log("MIDDLEWARE FOR SINGLE ROUTE");
        },
        function() {
            error_log("ADDITIONAL MIDDLEWARE FOR SINGLE ROUTE");
        })
    ),
    '/hello/:name' => array('post' => array('Home:hello',
        function() {
            error_log("THIS ROUTE IS ONLY POST");
        }
    ))
));
```

We've tweaked the way routs are added lately and apparently didn't update all of the code examples.  I'll make sure they get updated.

**Comment by savdeep** [comment]
cool, thanks :+1:
