### ISSUE TITLE
Support for Slim 2.6 version

### ISSUE THREAD

**Issue by izhutaev-sugarcrm** [fortrabbit/slimcontroller#38]
Hey, thanks for great addition to Slim!
Any plans to update this package to use Slim 2.6+ version (https://github.com/slimphp/Slim/releases)?

Thanks!

**Comment by psol-polska** [comment]
I am also interested in

**Comment by yaworsw** [comment]
I've updated the slim dependency to be 2.* in slimcontroller version 0.4.3.

This will allow you to use newer versions of slim including 2.6.2.
