### ISSUE TITLE
Assigning conditions to route parameters

### ISSUE THREAD

**Issue by drinkynet** [fortrabbit/slimcontroller#39]
What would the syntax be for assigning conditions to route parameters through ```addRoutes()``` given the conditions example in the Slim docs:

```
$app = new \Slim\Slim();
$app->get('/archive/:year', function ($year) {
    echo "You are viewing archives from $year";
})->conditions(array('year' => '(19|20)\d\d'));
```

Without conditions parameter routes match more than they should and the route order then matters.

**Comment by yaworsw** [comment]
The `addControllerRoute` method returns the slim route that it creates thus allowing
  you call methods like via and condition on it.

    $app->addControllerRoute("/the/path", "className:methodName")
        ->via('GET')->condition(..);

  Unfortunately I do not believe that there is a way to call methods like `condition` on the route if you create it through `addRoutes`.
